png('plot3.png')
with(data1, plot(x = Time, y = Sub_metering_1, type = 'n', xlab = '', ylab = 'Energy sub metering'))
lines(data1$Time, data1$Sub_metering_1)
lines(data1$Time, data1$Sub_metering_3, col = 'blue')
lines(data1$Time, data1$Sub_metering_2, col = 'red')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = 'solid', lwd = '1', col = c('black', 'red', 'blue'), cex = 0.7)
dev.off()
