png('plot4.png')
par(mfrow = c(2,2))
par(mar = c(4, 4, 1, 1))
with(data1, plot(x = Time, y = Global_active_power, type = 'n', xlab = '', ylab = 'Global Active Power'))
lines(data1$Time, data1$Global_active_power)
with(data1, plot(x = Time, y = Voltage, type = 'n', xlab = 'datetime'))
lines(data1$Time, data1$Voltage)
with(data1, plot(x = Time, y = Sub_metering_1, type = 'n', xlab = '', ylab = 'Energy sub metering'))
lines(data1$Time, data1$Sub_metering_1)
lines(data1$Time, data1$Sub_metering_3, col = 'blue')
lines(data1$Time, data1$Sub_metering_2, col = 'red')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = 'solid', lwd = '1', col = c('black', 'red', 'blue'), cex = 0.5, seg.len = 1, adj = c(0, 0.1), box.lty = 0)
with(data1, plot(x = Time, y = Global_reactive_power, type = 'n', xlab = 'datetime'))
lines(data1$Time, data1$Global_reactive_power)
dev.off()